### ISSUE TITLE
Overrides the tab settings in VSCode

### ISSUE THREAD

**Issue by adegeo** [microsoft/vscode-docs-authoring#774] opened 2020-11-05 22:41 UTC
I've set VSCode to auto detect tab indentation (which detects Spaces: 2) yet with the docs pack extension installed it always forces 4 spaces on a tab.

[AB#332858](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/332858)

**Comment by nschonni** [comment] 2020-11-05 23:41
Duplicate of https://github.com/microsoft/vscode-docs-authoring/issues/671

**Comment by meganbradley** [comment] 2020-11-17 18:32
Closing as dupe.

**Closed by meganbradley** 2020-11-17 18:32 UTC
