### ISSUE TITLE
 multi-select support

### ISSUE THREAD

**Issue by meganbradley** [microsoft/vscode-docs-authoring#427] opened 2020-02-25 00:18 UTC
From a customer suggestion:

I’d like to request multi-select support in the Docs Authoring Pack for, for example, boldfacing text. In VS Code, you can press Alt to multi-select text. It would then be nice to be able to use DAP to bold all the selected text at once. (See attached screenshot of multi-select.)

**Comment by jamarw** [comment] 2020-02-26 18:12
Hi @meganbradley , @mamccrea .

I think this may be a dupe of issue [367](https://github.com/microsoft/vscode-docs-authoring/issues/367) which was picked-up and completed in January. I've attached a demo video to confirm this request is the same as 367 and if so, we'll close this one.  

Thanks!

![multi-select-menu](https://user-images.githubusercontent.com/11825888/75374086-79c17080-5880-11ea-8171-0ce187837fef.gif)

**Comment by bharney0** [comment] 2020-03-02 22:09
#401 resolved this issue. Closing this one out.

**Closed by bharney0** 2020-03-02 22:09 UTC
Labels: help wanted
