### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by IEvangelist** [microsoft/vscode-docs-authoring#567] opened 2020-05-05 16:54 UTC
- Issue Type: `Bug`
- Extension Name: `docs-preview`
- Extension Version: `0.3.47`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.2`

Not sure why this is happening

![image](https://user-images.githubusercontent.com/7679720/81093019-16c70800-8ec7-11ea-9914-5efdba834328.png)

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 778,
		"activateCallTime": 1,
		"activateResolvedTime": 3054,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "ms-vsliveshare.vsliveshare",
				"_lower": "ms-vsliveshare.vsliveshare"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		},
		{
			"name": "Error",
			"message": "Request failed with status code 503"
		}
	]
}
```

[AB#239471](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/239471)

[AB#239500](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/239500)

**Comment by adunndevster** [comment] 2020-05-08 20:43
@IEvangelist - I cannot reproduce this. Do you know how you may have gotten it?

**Comment by IEvangelist** [comment] 2020-05-11 12:59
> @IEvangelist - I cannot reproduce this. Do you know how you may have gotten it?

I selected **Extensions** > `@installed` and navigated to the **docs-preview** - I noticed it was reporting these errors. I have no idea. They are cleared up now, I wonder if it wasn't due to an internet connectivity issue - if that was the case, it would imply that the **docs-preview** makes an assumption that there is always the internet, and doesn't cleanly handle when there is not.

**Comment by bharney0** [comment] 2020-06-03 19:42
I do believe docs-preview needs a connection for <xref:> and :::code::: tags. We should look into handling the exception and posting a warning message to the user rather than having an unhandled exception.

**Comment by lamebrain** [comment] 2020-06-18 20:40
sync

**Comment by jamarw** [comment] 2020-06-26 16:57
Hi @IEvangelist , unfortunately we couldn't repro this.  Closing this issue but please ping us if you run into again.  Thanks

**Closed by jamarw** 2020-06-26 16:57 UTC
Labels: bug, help wanted
