### ISSUE TITLE
Repeatedly warned "docs-markdown extension only works on Markdown files"

### ISSUE THREAD

**Issue by gvashishtha** [microsoft/vscode-docs-authoring#448] opened 2020-03-05 15:30 UTC
Issue Type: <b>Bug</b>

I'm not sure, just try opening VS code with the docs-markdown extension installed. It will keep popping up in the bottom right, saying "docs-markdown extension only works on Markdown files," even when you have done nothing to invoke the extension.

Extension version: 0.2.55
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (1.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.93GB (1.81GB free)|
|VM|0%|
</details>

**Comment by exactmike** [comment] 2020-03-05 15:54
I think this is a duplicate of #441

**Comment by bharney0** [comment] 2020-03-05 17:44
@gvashishtha thank you for reporting this issue. We have been made aware of the problem and are in the process of patching the issue with PR #442. We will be releasing an update shortly.

**Closed** 2020-03-05 17:51 UTC
